# Generated by Django 4.2.21 on 2025-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('property_address', models.TextField(blank=True)),
                ('project_type', models.CharField(blank=True, max_length=255)),
                ('scope_of_work', models.TextField(blank=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('preferred_timeline', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=255)),
                ('budget_range', models.CharField(blank=True, max_length=255)),
                ('needs_estimate', models.BooleanField(default=False)),
                ('needs_financing', models.BooleanField(default=False)),
                ('appointment_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('conversation_history', models.JSONField(default=list)),
            ],
        ),
    ]
