# Generated by Django 4.2.21 on 2025-06-10 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_by', models.CharField(help_text='Who created this note', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_customer_visible', models.BooleanField(default=False, help_text='Can customer see this note?')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Phone Call')], max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField(help_text='When reminder was scheduled to be sent')),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_codes', models.TextField(help_text='Comma-separated postal codes')),
                ('is_active', models.BooleanField(default=True)),
                ('travel_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='needs_financing',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_timeline',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scope_of_work',
        ),
        migrations.AddField(
            model_name='appointment',
            name='budget',
            field=models.CharField(blank=True, help_text="Customer's budget range", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes after job completion', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Service address', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_rating',
            field=models.IntegerField(blank=True, help_text='Customer rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='house_stage',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('framing', 'Framing'), ('roof_level', 'Roof Level'), ('rough_plumbing', 'Rough Plumbing'), ('electrical', 'Electrical'), ('insulation', 'Insulation'), ('drywall', 'Drywall'), ('not_plastered', 'Not Plastered'), ('plastered', 'Plastered'), ('painted', 'Painted'), ('finished', 'Finished'), ('occupied', 'Occupied')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal team notes', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='project_description',
            field=models.TextField(blank=True, help_text='Detailed description of the project', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Scheduled appointment date and time', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeline',
            field=models.CharField(blank=True, help_text="Customer's preferred timeline", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='twilio_conversation_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, help_text='WhatsApp conversation history'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, help_text="Customer's full name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='needs_estimate',
            field=models.BooleanField(default=False, help_text='Customer requested written estimate'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(help_text="Customer's WhatsApp number", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project_type',
            field=models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('toilet', 'Toilet'), ('sink', 'Sink'), ('pipe', 'Pipe Repair'), ('leak', 'Leak Repair'), ('faucet', 'Faucet'), ('shower', 'Shower'), ('renovation', 'Renovation'), ('installation', 'Installation'), ('maintenance', 'Maintenance'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condominium'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial'), ('office', 'Office'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['phone_number'], name='bot_appoint_phone_n_7def80_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='bot_appoint_status_c61131_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_datetime'], name='bot_appoint_schedul_21b602_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='bot_appoint_created_138cbc_idx'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bot.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bot.appointment'),
        ),
    ]
