# Generated by Django 4.2.21 on 2025-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_appointmentnote_appointmentreminder_servicearea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_area',
            field=models.CharField(blank=True, help_text='Service area (e.g. Harare Hatfield)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project_type',
            field=models.CharField(blank=True, choices=[('bathroom_renovation', 'Bathroom Renovation'), ('new_plumbing_installation', 'New Plumbing Installation'), ('kitchen_renovation', 'Kitchen Renovation'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
