# Generated by Django 4.2.21 on 2025-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_appointment_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_plan',
            field=models.BooleanField(default=False, help_text='Customer requested written estimate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='site_visit',
            field=models.BooleanField(default=False, help_text='Customer requested written estimate'),
        ),
    ]
