# Generated by Django 4.2.21 on 2025-07-16 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_appointment_has_plan_appointment_site_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='house_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='bot.appointment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
