# Generated by Django 4.2.21 on 2025-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_appointment_house_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_datetime'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
