# Generated by Django 4.2.21 on 2025-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_1day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2hours_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_morning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
