# Generated by Django 4.2.21 on 2025-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_appointment_reminder_1day_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_1day_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_2hours_sent',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_1_day_sent',
            field=models.BooleanField(default=False, help_text='1-day reminder sent'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2_hours_sent',
            field=models.BooleanField(default=False, help_text='2-hour reminder sent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reminder_morning_sent',
            field=models.BooleanField(default=False, help_text='Morning reminder sent'),
        ),
    ]
