# Generated by Django 4.2.21 on 2025-08-24 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_appointment_reminder_1day_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Appointment duration'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Appointment end date and time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='has_plan',
            field=models.BooleanField(default=False, help_text='Customer has existing plans'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='site_visit',
            field=models.BooleanField(default=False, help_text='Customer requested site visit'),
        ),
    ]
