# Generated by Django 4.2.21 on 2025-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_appointment_options_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='plan_file',
            field=models.FileField(blank=True, help_text="Customer's uploaded plan document", null=True, upload_to='customer_plans/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plan_notes',
            field=models.TextField(blank=True, help_text='Notes about the uploaded plan from plumber review', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plan_status',
            field=models.CharField(blank=True, choices=[('pending_upload', 'Pending Plan Upload'), ('plan_uploaded', 'Plan Uploaded'), ('plan_reviewed', 'Plan Reviewed by Plumber'), ('ready_to_book', 'Ready to Book')], help_text='Current status of plan processing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plan_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when plan was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plumber_contact_number',
            field=models.CharField(default='+27610318200', help_text='Direct contact number for the assigned plumber', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plumber_contacted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when plumber was notified about plan', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('business', 'Business'), ('apartment', 'Apartment'), ('condo', 'Condominium'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial'), ('office', 'Office'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
