# Generated by Django 4.2.21 on 2025-09-27 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0011_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('site_visit', 'Site Visit'), ('job_appointment', 'Job Appointment')], default='site_visit', help_text='Type of appointment: site visit or job appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_plumber',
            field=models.ForeignKey(blank=True, help_text='Plumber assigned to this job appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the job was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_description',
            field=models.TextField(blank=True, help_text='Detailed description of the job work to be performed'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_duration_hours',
            field=models.IntegerField(default=4, help_text='Duration of the job appointment in hours'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_materials_needed',
            field=models.TextField(blank=True, help_text='List of materials and tools needed for the job'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_scheduled_datetime',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for the job appointment', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_schedule', 'Pending Schedule'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_applicable', help_text='Status of the job appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_site_visit',
            field=models.ForeignKey(blank=True, help_text='The parent site visit that led to this job appointment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_appointments', to='bot.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plumber_assessment',
            field=models.TextField(blank=True, help_text="Plumber's assessment after site visit"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='site_visit_completed',
            field=models.BooleanField(default=False, help_text='Whether the site visit has been completed'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='site_visit_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the site visit was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='site_visit_notes',
            field=models.TextField(blank=True, help_text='Notes from the completed site visit'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_type'], name='bot_appoint_appoint_2db6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['job_status'], name='bot_appoint_job_sta_8ccd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['job_scheduled_datetime'], name='bot_appoint_job_sch_f2dc20_idx'),
        ),
    ]
