# Generated by Django 4.2.21 on 2025-10-21 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0012_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Bathroom Renovation')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this template is for')),
                ('project_type', models.CharField(choices=[('bathroom_renovation', 'Bathroom Renovation'), ('kitchen_renovation', 'Kitchen Renovation'), ('new_plumbing_installation', 'New Plumbing Installation'), ('general', 'General Plumbing')], default='general', max_length=50)),
                ('default_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-use_count', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('fixtures', 'Fixtures'), ('pipes', 'Pipes & Fittings'), ('labor', 'Labor'), ('materials', 'Materials'), ('hardware', 'Hardware'), ('other', 'Other')], default='materials', max_length=50)),
                ('is_optional', models.BooleanField(default=False, help_text='Mark if this item is optional')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this item')),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.quotationtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_hours', models.IntegerField(default=4)),
                ('description', models.TextField()),
                ('materials_needed', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bot.appointment')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
