# Generated by Django 4.2.21 on 2025-10-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_quotation_options_quotation_transport_cost_and_more'),  # Replace with your last migration
    ]

    operations = [
        # Step 1: Allow NULL temporarily and set existing False values to NULL
        migrations.RunSQL(
            """
            ALTER TABLE bot_appointment 
            ALTER COLUMN has_plan DROP NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Step 2: Set existing False values to NULL for incomplete appointments
        migrations.RunSQL(
            """
            UPDATE bot_appointment 
            SET has_plan = NULL 
            WHERE has_plan = false 
              AND customer_area IS NULL 
              AND scheduled_datetime IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Step 3: Alter the field definition
        migrations.AlterField(
            model_name='appointment',
            name='has_plan',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]    
