# Generated by Django 4.2.21 on 2026-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_fix_has_plan_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_phone_n_7def80_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_status_c61131_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_schedul_21b602_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_created_138cbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_appoint_2db6dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_job_sta_8ccd4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bot_appoint_job_sch_f2dc20_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup_count',
            field=models.IntegerField(default=0, help_text='Number of follow-ups sent'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup_stage',
            field=models.CharField(choices=[('none', 'No Follow-up Needed'), ('day_1', '1 Day Follow-up'), ('day_3', '3 Day Follow-up'), ('week_1', '1 Week Follow-up'), ('week_2', '2 Week Follow-up'), ('month_1', '1 Month Follow-up'), ('completed', 'Follow-up Completed'), ('responded', 'Customer Responded')], default='none', help_text='Current follow-up stage', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_lead_active',
            field=models.BooleanField(default=True, help_text='Whether this lead is still active for follow-ups'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_customer_response',
            field=models.DateTimeField(blank=True, help_text='Last time customer sent a message', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_followup_sent',
            field=models.DateTimeField(blank=True, help_text='Last time we sent a follow-up message', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lead_marked_inactive_at',
            field=models.DateTimeField(blank=True, help_text='When lead was marked as inactive', null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_lead_active', 'followup_stage', 'last_customer_response'], name='bot_appoint_is_lead_6bbcda_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['last_followup_sent'], name='bot_appoint_last_fo_83b458_idx'),
        ),
    ]
