# Generated by Django 4.2.21 on 2026-02-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_add_followup_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automatic_followup_count',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_automatic_followup',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_automatic_followup_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_manual_followup_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='manual_followup_count',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='manual_followup_paused',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='manual_followup_paused_until',
        ),
    ]
