# Generated by Codex on 2026-02-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0018_remove_appointment_automatic_followup_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="chatbot_paused",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="follow_up_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("waiting_customer", "Waiting Customer"),
                    ("completed", "Completed"),
                    ("closed_lost", "Closed Lost"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_contacted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_inbound_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_outbound_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="lead_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("cold", "Cold"),
                    ("warm", "Warm"),
                    ("hot", "Hot"),
                    ("very_hot", "Very Hot"),
                ],
                db_index=True,
                default="cold",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="next_follow_up_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="WhatsAppInboundEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=128, unique=True)),
                ("sender", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsapp_inbound", "WhatsApp Inbound"),
                            ("whatsapp_outbound", "WhatsApp Outbound"),
                            ("note", "Note"),
                            ("status_change", "Status Change"),
                            ("bot_paused", "Bot Paused"),
                            ("bot_resumed", "Bot Resumed"),
                            ("appointment", "Appointment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_answer", "No Answer"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("booked", "Booked"),
                            ("follow_up_later", "Follow Up Later"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("appointment_at", models.DateTimeField(blank=True, null=True)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_interactions",
                        to="bot.appointment",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["appointment", "-created_at"], name="bot_leadint_appointm_44ac1f_idx"),
                    models.Index(fields=["activity_type", "-created_at"], name="bot_leadint_activit_8244c4_idx"),
                ],
            },
        ),
    ]

