# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0019_add_lead_scoring_and_interactions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leadinteraction",
            new_name="bot_leadint_appoint_ecde0f_idx",
            old_name="bot_leadint_appointm_44ac1f_idx",
        ),
        migrations.RenameIndex(
            model_name="leadinteraction",
            new_name="bot_leadint_activit_b0f299_idx",
            old_name="bot_leadint_activit_8244c4_idx",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="plumber_contact_number",
            field=models.CharField(
                default="+263610318200",
                help_text="Direct contact number for the assigned plumber",
                max_length=20,
            ),
        ),
    ]

