# Generated by Django 4.2.21 on 2026-02-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_priority_lead_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pricing_overview_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='plumber_contact_number',
            field=models.CharField(default='+27610318200', help_text='Direct contact number for the assigned plumber', max_length=20),
        ),
    ]
