# Generated by Django 4.2.21 on 2026-02-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0022_appointment_pricing_overview_sent_and_more"),
        ("bot", "0022_remove_leadinteraction_and_add_summary_fields"),
    ]

    operations = []
