# Generated by Django 4.2.21 on 2026-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_merge_20260225_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sent_pricing_intents',
            field=models.JSONField(blank=True, default=list, help_text='List of pricing intents already sent to this customer'),
        ),
    ]
