# Generated by Django 4.2.21 on 2026-03-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_appointment_plan_followup_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='plan_followup_attempts',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='plan_followup_not_before',
        ),
    ]
