# Generated by Django 4.2.21 on 2026-06-18 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0031_appointment_delay_followup_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='delay_followup_due_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='14 days after delay_signal_detected_at — plumber follow-up deadline.', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='delay_signal_detected_at',
            field=models.DateTimeField(blank=True, help_text='When the delay signal was first detected.', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_delayed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when customer signalled not ready yet.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='plumber_contact_number',
            field=models.CharField(default='+263774819901', help_text='Direct contact number for the assigned plumber', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], db_index=True, max_length=10)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('subject', models.CharField(blank=True, default='', help_text='Email subject (email only)', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_followups', to='bot.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='bot_schedul_status_877c29_idx')],
            },
        ),
    ]
