# Generated by Django 4.2.21 on 2026-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_alter_appointment_delay_followup_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledfollowup',
            name='template_key',
            field=models.CharField(blank=True, default='', help_text='email_catalog key — when set, the dispatcher renders that template fresh at send time instead of using subject/message.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledfollowup',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
