# Generated by Django 4.2.21 on 2026-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_appointment_fk_on_delete_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinboundevent',
            name='message_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappinboundevent',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinboundevent',
            name='referral',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
