# Generated by Django 4.2.21 on 2026-06-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_whatsappinboundevent_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ctwa_entry_at',
            field=models.DateTimeField(blank=True, help_text='Start of the 72h CTWA messaging window', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ctwa_referral',
            field=models.JSONField(blank=True, help_text='Full CTWA referral object from the ad click', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ctwa_source_id',
            field=models.CharField(blank=True, default='', help_text='Meta ad source_id for a CTWA lead', max_length=64),
        ),
    ]
