# Generated by Django 4.2.21 on 2026-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_scheduledreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(default='General', help_text='Grouping shown in the Scenario Lab (e.g. Pricing, Booking flow, Objections)', max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField(help_text="Scenario text: '>' customer lines, 'expect:'/'reject:' assertions")),
                ('is_active', models.BooleanField(default=True)),
                ('last_result', models.JSONField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
