# Generated by Django 4.2.21 on 2026-07-10 16:52

from django.db import migrations, models
from django.db.models import F


def backfill_booked_at(apps, schema_editor):
    """Seed booked_at for already-confirmed appointments so the Conversations
    date filter has a date to measure. Best available proxy is the scheduled
    site-visit time, falling back to when the row was last updated."""
    Appointment = apps.get_model('bot', 'Appointment')
    confirmed = Appointment.objects.filter(status='confirmed', booked_at__isnull=True)
    confirmed.filter(scheduled_datetime__isnull=False).update(booked_at=F('scheduled_datetime'))
    confirmed.filter(scheduled_datetime__isnull=True).update(booked_at=F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_testscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the lead converted to a booking (status first became confirmed)', null=True),
        ),
        migrations.RunPython(backfill_booked_at, migrations.RunPython.noop),
    ]
