# Generated by Django 4.2.21 on 2026-07-15 01:31

import bot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0039_appointment_booked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(help_text="Customer's WhatsApp number", max_length=50),
        ),
        migrations.CreateModel(
            name='TenantWhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('business_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token', models.TextField(blank=True, default='')),
                ('verify_token', models.CharField(blank=True, default='', max_length=128)),
                ('display_number', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_channels', to='bot.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plumber_name', models.CharField(blank=True, default='', max_length=100)),
                ('plumber_contact', models.CharField(blank=True, default='', max_length=32)),
                ('business_whatsapp', models.CharField(blank=True, default='', max_length=32)),
                ('location_line', models.CharField(blank=True, default='', max_length=255)),
                ('business_hours', models.JSONField(blank=True, null=True)),
                ('timezone_name', models.CharField(blank=True, default='Africa/Johannesburg', max_length=64)),
                ('excluded_areas', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(blank=True, default='US$', max_length=8)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('sales_profile_md', models.TextField(blank=True, default='')),
                ('faq_facts', models.JSONField(blank=True, default=dict)),
                ('scripts', models.JSONField(blank=True, default=dict)),
                ('licensed_claim_enabled', models.BooleanField(default=False)),
                ('email_from_name', models.CharField(blank=True, default='', max_length=100)),
                ('email_sender', models.EmailField(blank=True, default='', max_length=254)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bot.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='appointmentnote',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='scheduledfollowup',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='scheduledreminder',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappinboundevent',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bot.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
