# Generated by Django 4.2.21 on 2026-07-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_seed_homebase_tenant_and_backfill'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone_number'), name='uniq_phone_per_tenant'),
        ),
    ]
