# Generated by Django 4.2.21 on 2026-07-15 02:14

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_appointment_uniq_phone_per_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='appointmentnote',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='scheduledfollowup',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='scheduledreminder',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
        migrations.AlterField(
            model_name='whatsappinboundevent',
            name='tenant',
            field=models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant'),
        ),
    ]
