# Generated by Django 4.2.21 on 2026-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_seed_homebase_faq_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='plumber_contact_number',
            field=models.CharField(blank=True, default='', help_text='Direct contact number for the assigned plumber (overrides the tenant default)', max_length=20),
        ),
    ]
