# Generated by Django 4.2.21 on 2026-07-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0046_alter_appointment_plumber_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=40)),
                ('variant', models.CharField(blank=True, default='', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('short_label', models.CharField(blank=True, default='', max_length=120)),
                ('supply', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('labour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('allin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parts', models.JSONField(blank=True, default=list)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='bot.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'family', 'variant'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantpriceitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'family', 'variant'), name='uniq_price_item_per_tenant'),
        ),
    ]
