# Generated by Django 4.2.21 on 2026-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0049_tub_size_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='location_area',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
