# Generated by Django 4.2.21 on 2026-07-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0051_seed_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.SlugField(max_length=80)),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=120)),
                ('price_line', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('story', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='bot.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantportfolioitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_id'), name='uniq_portfolio_item_per_tenant'),
        ),
    ]
