# Generated by Django 4.2.21 on 2026-07-15 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0053_seed_homebase_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting owner'), ('submitted', 'Submitted — awaiting review'), ('approved', 'Approved & applied'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='bot.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
