# Generated by Django 4.2.21 on 2026-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0054_tenantintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscenario',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='testscenario',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_scenario_per_tenant'),
        ),
    ]
