# Generated by Django 4.2.21 on 2026-07-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0056_backfill_homebase_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantportfolioitem',
            name='pair_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
