# Generated by Django 4.2.21 on 2026-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0057_tenantportfolioitem_pair_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lead_source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='facebook_ad / instagram_ad / facebook / instagram / google_search / referral / flyer / whatsapp_status / direct', max_length=30),
        ),
    ]
