# Generated by Django 4.2.21 on 2026-07-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0059_backfill_lead_sources'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantportfolioitem',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='portfolio_title_required'),
        ),
    ]
