# Generated by Django 4.2.21 on 2026-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0060_tenantportfolioitem_portfolio_title_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantportfolioitem',
            name='price_refs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
