# Generated by Django 4.2.21 on 2026-08-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0065_tenantsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='twilio_conversation_sid',
        ),
    ]
