# Generated by Django 4.2.21 on 2026-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0066_remove_appointment_twilio_conversation_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='customer_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
