# Generated by Django 4.2.21 on 2026-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0068_seed_homebase_customer_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='section',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='letterhead',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
