# Generated by Django 4.2.21 on 2026-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0070_seed_barmak_letterhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='quantity_text',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
