# Generated by Django 4.2.21 on 2026-08-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0071_quotationitem_quantity_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantportfolioitem',
            name='vision_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
