# Generated by Django 4.2.21 on 2026-08-28 14:51

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0072_tenantportfolioitem_vision_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSendCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('recipient', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('billable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('pricing_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('category', models.CharField(blank=True, db_index=True, max_length=40)),
                ('pricing_model', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('error_codes', models.CharField(blank=True, max_length=120)),
                ('was_ctwa_lead', models.BooleanField(db_index=True, default=False)),
                ('hours_since_ctwa_entry', models.FloatField(blank=True, null=True)),
                ('hours_since_last_inbound', models.FloatField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_costs', to='bot.appointment')),
                ('tenant', models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, to='bot.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
