# Generated by Django 4.2.21 on 2026-09-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0073_whatsapp_send_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
