# Generated by Django 4.2.21 on 2026-09-01 13:37

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def carry_over_past_sends(apps, schema_editor):
    """Don't let a 2-day reminder whose moment has passed fire again.

    Until now both the 2-day and the 1-day reminder wrote reminder_1_day_sent,
    so for an existing row that flag means "one of the pair went out" and there
    is no way to tell which. Splitting the column leaves the new one False, which
    would reopen the 2-day reminder for any appointment still sitting inside its
    +/-10 minute send window.

    So: where the 2-day moment has ALREADY passed, carry the old flag across —
    it can only mean the reminder is behind us. Where the appointment is still
    more than two days out, nothing legitimately set that flag yet, so leave the
    new column False and let the 2-day reminder fire properly.
    """
    Appointment = apps.get_model('bot', 'Appointment')
    Appointment.objects.filter(
        reminder_1_day_sent=True,
        scheduled_datetime__isnull=False,
        scheduled_datetime__lte=timezone.now() + timedelta(days=2),
    ).update(reminder_2_days_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0074_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_2_days_sent',
            field=models.BooleanField(default=False, help_text='2-day reminder sent'),
        ),
        # Reversing just drops the column, so the backfill needs no inverse.
        migrations.RunPython(carry_over_past_sends, migrations.RunPython.noop),
    ]
