# Generated by Django 4.2.21 on 2026-09-02 17:20

import bot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0076_consultation_fee_waived'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sent_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SiteVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fallback_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_via', models.CharField(blank=True, choices=[('app', 'In-app button'), ('link', 'Emailed link')], default='', max_length=10)),
                ('outcome', models.CharField(blank=True, choices=[('went_ahead', 'Went ahead'), ('no_show', 'No-show'), ('rescheduled', 'Rescheduled'), ('not_proceeding', 'Lead not proceeding')], default='', max_length=20)),
                ('expectation', models.CharField(blank=True, choices=[('specific_date', 'Specific date'), ('timeframe', 'Rough timeframe'), ('unknown', "Didn't say")], default='', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('expected_timeframe', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('two_weeks', 'Within 2 weeks'), ('this_month', 'This month'), ('one_to_three_months', '1 to 3 months'), ('exploring', 'Just exploring')], default='', max_length=25)),
                ('job_notes', models.TextField(blank=True, default='')),
                ('sequence', models.CharField(choices=[('awaiting_form', 'Awaiting the form'), ('confirm', 'Confirmation before the job date'), ('asks', 'Ask sequence'), ('done', 'Finished'), ('cold', 'Marked cold'), ('stopped', 'Stopped')], db_index=True, default='awaiting_form', max_length=20)),
                ('ask_count', models.PositiveSmallIntegerField(default=0)),
                ('last_ask_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cold_notified_at', models.DateTimeField(blank=True, null=True)),
                ('no_email_notified_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_report', to='bot.appointment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, related_name='site_visit_reports', to='bot.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sequence', 'next_action_at'], name='bot_sitevis_sequenc_c66712_idx')],
            },
        ),
    ]
