# Generated by Django 4.2.21 on 2026-09-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0077_site_visit_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='is_global',
            field=models.BooleanField(db_index=True, default=False, help_text='Platform template offered to every tenant, read-only to them'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('cold', 'Cold')], default='draft', max_length=20),
        ),
    ]
