# Generated by Django 4.2.21 on 2026-09-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0079_quote_status_rejected_to_cold'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='quote_email_mode',
            field=models.CharField(choices=[('platform', 'Send from our configured address'), ('manual', 'Open a draft in my email app')], default='platform', max_length=10),
        ),
    ]
