# Generated by Django 4.2.21 on 2026-09-05 21:30

import bot.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0080_quote_email_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_received_at', models.DateTimeField(blank=True, null=True)),
                ('plumber_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.PositiveSmallIntegerField(default=0)),
                ('plumber_form_completed_at', models.DateTimeField(blank=True, null=True)),
                ('quote_status', models.CharField(blank=True, choices=[('', 'Not known yet'), ('sent_confirmed', 'Plumber confirmed the quote was sent'), ('assumed', 'Assumed sent')], default='', max_length=20)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. What the plumber quoted.', max_digits=12, null=True)),
                ('lead_followup_sent_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_quote_request', to='bot.appointment')),
                ('tenant', models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, related_name='plan_quote_requests', to='bot.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['plumber_email_sent_at'], name='bot_planquo_plumber_ba6766_idx'), models.Index(fields=['plumber_form_completed_at'], name='bot_planquo_plumber_5adf21_idx')],
            },
        ),
    ]
