# Generated by Django 4.2.21 on 2026-09-05 22:42

import bot.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0081_planquoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('proposed', 'Proposed, awaiting the lead'), ('confirmed', 'Confirmed by the lead'), ('declined', 'Declined by the lead'), ('lapsed', 'No answer, given up')], db_index=True, default='proposed', max_length=12)),
                ('email_opt_in', models.CharField(choices=[('unknown', 'Not asked yet'), ('yes', 'Gave an address'), ('declined', 'Refused')], default='unknown', max_length=10)),
                ('portfolio_sent_channel', models.CharField(choices=[('none', 'Not sent'), ('email', 'Emailed'), ('whatsapp', 'Sent on WhatsApp')], default='none', max_length=10)),
                ('checkin_1_sent_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_2_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_proposal', to='bot.appointment')),
                ('tenant', models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, related_name='visit_proposals', to='bot.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'target_date'], name='bot_visitpr_state_900da5_idx')],
            },
        ),
    ]
