# Generated by Django 4.2.21 on 2026-09-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0082_visitproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquoterequest',
            name='expectation',
            field=models.CharField(blank=True, choices=[('specific_date', 'Specific date'), ('timeframe', 'Rough timeframe'), ('unknown', "Didn't say")], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='planquoterequest',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planquoterequest',
            name='expected_timeframe',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP'), ('two_weeks', 'Within 2 weeks'), ('this_month', 'This month'), ('one_to_three_months', '1 to 3 months'), ('exploring', 'Just exploring')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='planquoterequest',
            name='job_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planquoterequest',
            name='outcome',
            field=models.CharField(blank=True, choices=[('quoting', 'Quoting from the plan'), ('needs_visit', 'Plan is not enough, book a visit'), ('not_proceeding', 'Lead not proceeding')], default='', max_length=20),
        ),
    ]
