# Generated by Django 4.2.21 on 2026-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0083_planquoterequest_expectation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planquoterequest',
            name='timeline_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
