# Generated by Django 4.2.21 on 2026-09-07 09:05

import bot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0084_planquoterequest_timeline_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('quoting', 'Quoting over the phone'), ('needs_visit', 'Needs a site visit first'), ('not_proceeding', 'Lead not proceeding')], default='', max_length=20)),
                ('expectation', models.CharField(blank=True, choices=[('specific_date', 'Specific date'), ('timeframe', 'Rough timeframe'), ('unknown', "Didn't say")], default='', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('expected_timeframe', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('two_weeks', 'Within 2 weeks'), ('this_month', 'This month'), ('one_to_three_months', '1 to 3 months'), ('exploring', 'Just exploring')], default='', max_length=25)),
                ('job_notes', models.TextField(blank=True, default='')),
                ('customer_area', models.CharField(blank=True, default='', max_length=120)),
                ('quote_status', models.CharField(blank=True, choices=[('', 'Not known yet'), ('sent_confirmed', 'Plumber confirmed the quote was sent'), ('assumed', 'Assumed sent')], default='', max_length=20)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_followup_sent_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_quote_request', to='bot.appointment')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_quotes_completed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, default=bot.models.get_default_tenant_id, on_delete=django.db.models.deletion.PROTECT, related_name='phone_quote_requests', to='bot.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['form_completed_at'], name='bot_phonequ_form_co_9410bc_idx'), models.Index(fields=['lead_followup_sent_at'], name='bot_phonequ_lead_fo_5f3dba_idx')],
            },
        ),
    ]
