# Generated by Django 4.2.21 on 2026-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0087_template_item_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pending_send',
            field=models.JSONField(blank=True, help_text='In-flight delayed bot reply awaiting send, or an intercept tombstone', null=True),
        ),
    ]
