# Generated by Django 4.2.21 on 2026-09-17 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0088_appointment_pending_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('post_visit_confirm', 'Post-visit confirmation'), ('post_visit_ask', 'Post-visit follow-up'), ('post_visit_handback', 'Post-visit handback'), ('quote_sent', 'Quote sent'), ('quote_followup', 'Quote follow-up'), ('plan_quote_plumber', 'Plan to quote (plumber)'), ('visit_checkin', 'Site-visit check-in'), ('site_visit_form', 'Site-visit debrief form'), ('reminder', 'Appointment reminder'), ('delay', 'Delay re-engagement'), ('booking', 'Booking confirmation'), ('plumber_alert', 'Plumber alert'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('to_role', models.CharField(choices=[('customer', 'Customer'), ('plumber', 'Plumber'), ('operator', 'Operator'), ('other', 'Other')], default='other', max_length=16)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('open_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='bot.appointment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='bot.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'category', '-created_at'], name='bot_sentema_tenant__42deea_idx')],
            },
        ),
    ]
