# Generated by Django 4.2.21 on 2026-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0089_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='job_end_datetime',
            field=models.DateTimeField(blank=True, help_text='End of a multi-day job (blank = single-day job)', null=True),
        ),
    ]
