# Generated by Django 4.2.21 on 2026-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0091_sitevisitreport_sequence_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='category',
            field=models.CharField(choices=[('post_visit_confirm', 'Post-visit confirmation'), ('post_visit_ask', 'Post-visit follow-up'), ('post_visit_handback', 'Post-visit handback'), ('quote_sent', 'Quote sent'), ('quote_followup', 'Quote follow-up'), ('plan_quote_plumber', 'Plan to quote (plumber)'), ('visit_checkin', 'Site-visit check-in'), ('site_visit_form', 'Site-visit debrief form'), ('reminder', 'Appointment reminder'), ('delay', 'Delay re-engagement'), ('booking', 'Booking confirmation'), ('followup', 'Follow-up'), ('plumber_alert', 'Plumber alert'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
