# Generated by Django 4.2.21 on 2026-09-24 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0093_clear_chat_saved_as_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='HomeX Media', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Unmatched Velocity', max_length=80)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', help_text='Where tenants reply about billing. Also gets a Bcc copy of every invoice and receipt sent.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('currency', models.CharField(default='US$', max_length=8)),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_terms_days', models.PositiveIntegerField(default=7)),
                ('payment_details', models.TextField(blank=True, default='', help_text='Bank account, EcoCash number and so on. Printed on every invoice.')),
                ('footer_note', models.CharField(blank=True, default='', max_length=255)),
                ('reminder_days', models.CharField(default='14,7', help_text='Days before the due date to remind the tenant, e.g. 14,7. They are also reminded on the day.', max_length=40)),
                ('reminder_time', models.TimeField(default=datetime.time(7, 0))),
                ('subscription_breakdown', models.TextField(blank=True, default='WhatsApp AI sales assistant | answers 24/7, qualifies leads | 40\nBooking and scheduling | site visits, calendar, reminders | 15\nAutomated follow-ups | WhatsApp and email | 15\nQuotes and documents | quote builder, PDFs, templates | 10\nDashboard and lead management | | 10\nHosting, WhatsApp number and support | | 10', help_text='One per line: Feature | what it covers | percent. The percents must add up to 100.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('void', 'Void')], db_index=True, default='draft', max_length=8)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='US$', max_length=8)),
                ('bill_to_name', models.CharField(max_length=160)),
                ('bill_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('issuer', models.JSONField(blank=True, default=dict)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_days', models.CharField(blank=True, default='', help_text='Leave blank to use the default from Billing details.', max_length=40)),
                ('reminder_log', models.JSONField(blank=True, default=dict)),
                ('unpaid_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('switch_off_on', models.DateField(blank=True, null=True)),
                ('account_paused_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_invoices', to='bot.tenant')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='category',
            field=models.CharField(choices=[('post_visit_confirm', 'Post-visit confirmation'), ('post_visit_ask', 'Post-visit follow-up'), ('post_visit_handback', 'Post-visit handback'), ('quote_sent', 'Quote sent'), ('quote_followup', 'Quote follow-up'), ('plan_quote_plumber', 'Plan to quote (plumber)'), ('visit_checkin', 'Site-visit check-in'), ('site_visit_form', 'Site-visit debrief form'), ('reminder', 'Appointment reminder'), ('delay', 'Delay re-engagement'), ('booking', 'Booking confirmation'), ('followup', 'Follow-up'), ('plumber_alert', 'Plumber alert'), ('billing', 'Billing (invoice or receipt)'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('ecocash', 'EcoCash'), ('innbucks', 'InnBucks'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='bank', max_length=12)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_void', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bot.platforminvoice')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.platforminvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
