# Generated by Django 4.2.21 on 2026-09-24 13:22

from django.db import migrations, models


# The generic Plumbot invoice the owner asked for (2026-09-24), seeded as the
# default template so New invoice starts from it the moment this deploys: the
# US$150 subscription with the feature breakdown, and the US$10 website as an
# ordinary line the client pays (US$160 in all).
# Written out here rather than imported from models.PLUMBOT_STANDARD_TEMPLATE:
# a migration must keep meaning what it meant when it ran.
PLUMBOT_STANDARD = {
    'name': 'Plumbot Standard',
    'is_default': True,
    'lines': [
        {'description': 'Plumbot monthly subscription, {month}', 'quantity': '1',
         'unit_price': '150.00', 'with_breakdown': True},
        {'description': 'Business website, hosting and upkeep', 'quantity': '1',
         'unit_price': '10.00', 'with_breakdown': False},
    ],
}


def seed_plumbot_standard(apps, schema_editor):
    Template = apps.get_model('bot', 'PlatformInvoiceTemplate')
    if not Template.objects.filter(name=PLUMBOT_STANDARD['name']).exists():
        Template.objects.create(**PLUMBOT_STANDARD)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0094_platform_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.RunPython(seed_plumbot_standard, migrations.RunPython.noop),
    ]
