# Generated by Django 4.2.21 on 2026-09-24 13:53

from decimal import Decimal
from django.db import migrations, models


def lift_zero_fee(apps, schema_editor):
    """The owner's US$150 subscription (2026-09-24) as the default fee. A
    Billing details row created before this, by a visit to Billing, holds the
    old default of 0; lift only that. A fee the operator actually set on the
    page (anything but 0) is left exactly as it is."""
    Profile = apps.get_model('bot', 'PlatformBillingProfile')
    Profile.objects.filter(default_monthly_fee=0).update(default_monthly_fee=Decimal('150.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0095_billing_invoice_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbillingprofile',
            name='default_monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
        migrations.RunPython(lift_zero_fee, migrations.RunPython.noop),
    ]
