# Generated by Django 4.2.21 on 2026-09-24 14:37

from django.db import migrations, models


# The split as first shipped (migration 0094), and the same split without the
# WhatsApp number: the client brings their own number, so the invoice must not
# read as charging for one (owner, 2026-09-24). Written out, not imported, so
# this migration keeps meaning what it meant when it ran.
OLD_DEFAULT = (
    'WhatsApp AI sales assistant | answers 24/7, qualifies leads | 40\n'
    'Booking and scheduling | site visits, calendar, reminders | 15\n'
    'Automated follow-ups | WhatsApp and email | 15\n'
    'Quotes and documents | quote builder, PDFs, templates | 10\n'
    'Dashboard and lead management | | 10\n'
    'Hosting, WhatsApp number and support | | 10')
NEW_DEFAULT = OLD_DEFAULT.replace(
    'Hosting, WhatsApp number and support', 'Hosting, updates and support')


def rename_untouched_default(apps, schema_editor):
    """Update a saved split only while it is still the untouched old default.
    A split the operator edited is theirs and is left alone, and invoices
    already issued keep the breakdown frozen on their lines."""
    Profile = apps.get_model('bot', 'PlatformBillingProfile')
    Profile.objects.filter(subscription_breakdown=OLD_DEFAULT).update(
        subscription_breakdown=NEW_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0096_billing_default_fee_150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbillingprofile',
            name='subscription_breakdown',
            field=models.TextField(blank=True, default='WhatsApp AI sales assistant | answers 24/7, qualifies leads | 40\nBooking and scheduling | site visits, calendar, reminders | 15\nAutomated follow-ups | WhatsApp and email | 15\nQuotes and documents | quote builder, PDFs, templates | 10\nDashboard and lead management | | 10\nHosting, updates and support | | 10', help_text='One per line: Feature | what it covers | percent. The percents must add up to 100.'),
        ),
        migrations.RunPython(rename_untouched_default, migrations.RunPython.noop),
    ]
