# Generated by Django 4.2.21 on 2026-09-24 15:32

from django.db import migrations, models


# Payment details (owner, 2026-09-24). The bank text as first shipped; the
# bank text now, as short "Label: value" rows (FNB's product name "Business
# Zero Account" dropped, no sentence instructions); and EcoCash, printed first
# and only for Zimbabwean clients. Written out, not imported from models, so
# this migration keeps meaning what it meant when it ran.
FNB_ONLY = (
    'Bank transfer to HomeX Media\n'
    'FNB (First National Bank), Business Zero Account\n'
    'Account number: 63222994055\n'
    'Branch code: 250655\n'
    'SWIFT, for payments from outside South Africa: FIRNZAJJ')
BANK = (
    'Account name: HomeX Media\n'
    'Bank: FNB (First National Bank)\n'
    'Account number: 63222994055\n'
    'Branch code: 250655\n'
    'SWIFT code: FIRNZAJJ (from outside South Africa)')
ECOCASH = (
    'EcoCash: +263 78 631 8169\n'
    'Registered name: Joymanu Musabayana\n'
    'EcoCash fees: Paid by the sender')


def update_payment_details(apps, schema_editor):
    """Bring a saved Billing details row up to date without overwriting the
    operator's own words: the bank text is replaced only while it is still
    the untouched first default, and EcoCash is filled in only where empty.
    Invoices already issued keep what is frozen in their issuer snapshot."""
    Profile = apps.get_model('bot', 'PlatformBillingProfile')
    Profile.objects.filter(payment_details=FNB_ONLY).update(payment_details=BANK)
    Profile.objects.filter(ecocash_details='').update(ecocash_details=ECOCASH)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0097_billing_breakdown_no_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbillingprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='billing@homexmedia.com', help_text='Printed on invoices and receipts. Blank prints the billing email instead.', max_length=254),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='ecocash_details',
            field=models.TextField(blank=True, default='', help_text='EcoCash details. Printed first, above the bank details, on invoices to Zimbabwean clients only.'),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='zimbabwe_phone',
            field=models.CharField(blank=True, default='+263 78 631 8169', help_text='Printed on invoices to Zimbabwean clients only.', max_length=40),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='zimbabwe_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformbillingprofile',
            name='payment_details',
            field=models.TextField(blank=True, default='', help_text='Bank details. Printed on every invoice.'),
        ),
        migrations.AlterField(
            model_name='platformbillingprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Printed on every invoice. Leave blank for none.', max_length=40),
        ),
        migrations.RunPython(update_payment_details, migrations.RunPython.noop),
    ]
